const express=require('express');
const cors=require('cors');
const bcrypt=require('bcryptjs');
const jwt=require('jsonwebtoken');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const app=express();
app.use(cors());app.use(express.json({limit:'100kb'}));
const DB=path.join(__dirname,'data.json');
const SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_BEFORE_PRODUCTION';
const ADMIN_EMAIL=(process.env.ADMIN_EMAIL||'').trim().toLowerCase();
const ADMIN_SETUP_KEY=process.env.ADMIN_SETUP_KEY||'';
function load(){if(!fs.existsSync(DB))fs.writeFileSync(DB,JSON.stringify({users:[],withdrawals:[],history:[],settings:{withdrawalsEnabled:false,maintenance:false,minWithdrawal:100,payoutFund:0,bonusPointsPerRewardedAd:10}},null,2));return JSON.parse(fs.readFileSync(DB,'utf8'))}
function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}
function auth(req,res,next){try{const h=req.headers.authorization||'';const t=h.replace(/^Bearer\s+/i,'');req.user=jwt.verify(t,SECRET);next()}catch(e){res.status(401).json({error:'Unauthorized'})}}
function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Admin only'});next()}
function token(u){return jwt.sign({id:u.id,role:u.role,email:u.email},SECRET,{expiresIn:'7d'})}
function publicUser(u){return {id:u.id,name:u.name,email:u.email,role:u.role,coins:u.coins,bonusPoints:u.bonusPoints,payoutBalance:u.payoutBalance,createdAt:u.createdAt}}
function history(d,userId,type,amount,note){d.history.push({id:crypto.randomUUID(),userId,type,amount,note:note||'',createdAt:new Date().toISOString()})}
app.get('/api/health',(req,res)=>res.json({ok:true,service:'MB-Pay V5.1'}));
app.post('/api/auth/register',(req,res)=>{const d=load(),{name,email,password}=req.body||{};if(!name||!email||!password||String(password).length<8)return res.status(400).json({error:'Name, valid email and 8+ character password required'});const e=String(email).trim().toLowerCase();if(d.users.some(u=>u.email===e))return res.status(409).json({error:'Email already registered'});const role=(ADMIN_EMAIL&&e===ADMIN_EMAIL)?'admin':'user';const u={id:crypto.randomUUID(),name:String(name).trim().slice(0,80),email:e,password:bcrypt.hashSync(String(password),12),role,coins:0,bonusPoints:0,payoutBalance:0,createdAt:new Date().toISOString()};d.users.push(u);save(d);res.json({token:token(u),user:publicUser(u)})});
app.post('/api/auth/login',(req,res)=>{const d=load(),e=String(req.body?.email||'').trim().toLowerCase(),u=d.users.find(x=>x.email===e);if(!u||!bcrypt.compareSync(String(req.body?.password||''),u.password))return res.status(401).json({error:'Invalid email or password'});res.json({token:token(u),user:publicUser(u)})});
app.get('/api/me',auth,(req,res)=>{const d=load(),u=d.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:'User not found'});res.json(publicUser(u))});
app.get('/api/settings',auth,(req,res)=>{const d=load();res.json({withdrawalsEnabled:d.settings.withdrawalsEnabled,maintenance:d.settings.maintenance,minWithdrawal:d.settings.minWithdrawal,bonusPointsPerRewardedAd:d.settings.bonusPointsPerRewardedAd})});
app.get('/api/history',auth,(req,res)=>{const d=load();res.json(d.history.filter(x=>x.userId===req.user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,100))});
app.get('/api/history',auth,(req,res)=>{const d=load();res.json(d.history.filter(x=>x.userId===req.user.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,100))});
app.post('/api/rewards/daily',auth,(req,res)=>{const d=load(),u=d.users.find(x=>x.id===req.user.id);const today=new Date().toISOString().slice(0,10);if(u.lastDaily===today)return res.status(400).json({error:'Daily reward already claimed'});u.lastDaily=today;u.coins+=10;history(d,u.id,'daily_coins',10,'Daily in-app coins');save(d);res.json({coins:u.coins})});
// IMPORTANT: Rewarded ads only grant non-cash, non-transferable Bonus Points.
app.post('/api/rewards/ad-bonus',auth,(req,res)=>{const d=load(),u=d.users.find(x=>x.id===req.user.id);const amount=Math.max(1,Math.min(100,Number(req.body?.amount)||10));u.bonusPoints+=amount;history(d,u.id,'ad_bonus_points',amount,'Non-cash, non-transferable bonus');save(d);res.json({bonusPoints:u.bonusPoints})});
app.post('/api/withdrawals',auth,(req,res)=>{const d=load(),u=d.users.find(x=>x.id===req.user.id),amt=Number(req.body?.amount),upi=String(req.body?.upi||'').trim();if(!d.settings.withdrawalsEnabled)return res.status(400).json({error:'Withdrawal is OFF'});if(d.settings.maintenance)return res.status(400).json({error:'Maintenance mode'});if(!Number.isInteger(amt)||amt<d.settings.minWithdrawal||amt>u.payoutBalance)return res.status(400).json({error:'Invalid amount or insufficient payout balance'});if(!/^[A-Za-z0-9._-]{2,}@[A-Za-z0-9.-]{2,}$/.test(upi))return res.status(400).json({error:'Invalid UPI ID'});const w={id:'WD-'+crypto.randomBytes(5).toString('hex').toUpperCase(),userId:u.id,amount:amt,upi,status:'Pending',createdAt:new Date().toISOString()};u.payoutBalance-=amt;d.withdrawals.push(w);history(d,u.id,'withdrawal',-amt,'UPI withdrawal request '+w.id);save(d);res.json(w)});
app.get('/api/admin/users',auth,admin,(req,res)=>{const d=load();res.json(d.users.map(publicUser))});
app.get('/api/withdrawals',auth,admin,(req,res)=>{const d=load();res.json(d.withdrawals.map(w=>({...w,user:d.users.find(u=>u.id===w.userId)?publicUser(d.users.find(u=>u.id===w.userId)):null})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))) });
app.post('/api/withdrawals/:id/status',auth,admin,(req,res)=>{const d=load(),w=d.withdrawals.find(x=>x.id===req.params.id);if(!w)return res.status(404).json({error:'Not found'});const next=req.body?.status;if(!['Approved','Paid','Rejected'].includes(next))return res.status(400).json({error:'Invalid status'});if(w.status==='Paid'||w.status==='Rejected')return res.status(400).json({error:'Request already finalized'});if(next==='Paid'){if(d.settings.payoutFund<w.amount)return res.status(400).json({error:'Insufficient payout fund'});d.settings.payoutFund-=w.amount;history(d,w.userId,'withdrawal_paid',-w.amount,'UPI payment marked Paid by admin')}else if(next==='Rejected'){const u=d.users.find(x=>x.id===w.userId);if(u){u.payoutBalance+=w.amount;history(d,u.id,'withdrawal_returned',w.amount,'Rejected withdrawal returned')}}w.status=next;w.updatedAt=new Date().toISOString();save(d);res.json(w)});
app.get('/api/admin/users',auth,admin,(req,res)=>{const d=load();res.json(d.users.map(publicUser))});
// Real-money earning is credited by the owner/admin only after a separately verified eligible activity.
app.post('/api/admin/users/:id/payout-balance',auth,admin,(req,res)=>{const d=load(),u=d.users.find(x=>x.id===req.params.id),amount=Number(req.body?.amount),note=String(req.body?.note||'Verified activity payout').trim();if(!u||!Number.isInteger(amount)||amount===0)return res.status(400).json({error:'Invalid user or amount'});if(amount<0&&u.payoutBalance<Math.abs(amount))return res.status(400).json({error:'Insufficient user balance'});u.payoutBalance+=amount;history(d,u.id,amount>0?'verified_activity_earning':'admin_adjustment',amount,note);save(d);res.json(publicUser(u))});
app.post('/api/admin/users/:id/payout-balance',auth,admin,(req,res)=>{const d=load(),u=d.users.find(x=>x.id===req.params.id),amount=Number(req.body?.amount),note=String(req.body?.note||'Verified activity payout').trim();if(!u||!Number.isInteger(amount)||amount<=0)return res.status(400).json({error:'Invalid user or amount'});u.payoutBalance+=amount;d.history.push({id:crypto.randomUUID(),userId:u.id,type:'verified_activity_earning',amount,note,createdAt:new Date().toISOString()});save(d);res.json(publicUser(u))});
app.post('/api/admin/settings',auth,admin,(req,res)=>{const d=load();if(typeof req.body?.withdrawalsEnabled==='boolean')d.settings.withdrawalsEnabled=req.body.withdrawalsEnabled;if(typeof req.body?.maintenance==='boolean')d.settings.maintenance=req.body.maintenance;for(const k of ['minWithdrawal','payoutFund','bonusPointsPerRewardedAd'])if(Number.isInteger(req.body?.[k])&&req.body[k]>=0)d.settings[k]=req.body[k];save(d);res.json(d.settings)});
app.post('/api/admin/bootstrap',(req,res)=>{if(!ADMIN_SETUP_KEY||req.body?.key!==ADMIN_SETUP_KEY)return res.status(403).json({error:'Setup denied'});const d=load(),e=String(req.body?.email||'').trim().toLowerCase(),u=d.users.find(x=>x.email===e);if(!u)return res.status(404).json({error:'User not found'});u.role='admin';save(d);res.json({ok:true})});
app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(process.env.PORT||3000,()=>console.log('MB-Pay V5.1 running on port '+(process.env.PORT||3000)));
